name: ON-DISPATCH-TEST
run-name: Event handler for 'test' ( Triggered by ${{ github.event_name }} and run by ${{ github.actor }} )

on:
  repository_dispatch:
    types: [test]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  run-test:
    name: Run test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Echo
        run: |
          echo "### Test Passed" >> $GITHUB_STEP_SUMMARY
          echo "Payload: ${{ github.event.client_payload}}" >> $GITHUB_STEP_SUMMARY
