name: REPOSITORY-SECRETS-CHECK
run-name: Check Repo Secrets Exist ( ${{ github.event_name }} run by ${{ github.actor }} )

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository (or * for all)'
        required: false
        default: '*'
        type: string
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
  push:
    paths:
      - 'repo/repo-secrets.yml'

permissions:
  contents: read
  issues: write
  
jobs:

  get-config:
    name: Get config from GitOps
    if: ${{ github.event.head_commit.message != 'Initial commit' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.repos.outputs.SECRETS }}
    permissions:
      contents: read
    steps:

      - name: Check GITOPS_PAT secret exists
        env:
          gitops-secret: ${{ secrets.GITOPS_PAT }}
        if: ${{ env.gitops-secret == '' }}
        run: echo "echo the secret \"GITOPS_PAT\" has not been made; echo please go to \"settings \> secrets \> actions \> repository secrets\" to create it"

      - name: Checkout GitOps
        uses: actions/checkout@v4

      - name: Get Solution Repo's
        id: repos
        run: |
          filter=$(yq '.repoSecrets | filter(.repo == "${{ inputs.repo || '*' }}" )' repo/repo-secrets.yml -o=json | jq -c)
          secrets="{\"include\": $filter }"
          echo $secrets
          echo "SECRETS=$secrets" >> $GITHUB_OUTPUT

  do-checks:
    name: Run checks for repo secrets
    needs: [get-config]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-config.outputs.matrix) }}
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Node dependencies
        run: npm install

      - name: Check secret exists
        id: exists
        run: .github/actions-scripts/repo-secrets-check-exists.mjs
        env:
          GHA_TOKEN: ${{ secrets.GITOPS_PAT }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ matrix.repo }}
          SECRET_NAME: ${{ matrix.name }}

      - name: Secret is missing
        if: ${{ steps.exists.outputs.result != 'true' }}
        run: |
          echo "Secret ${{ matrix.name }} does not exist is ${{ matrix.repo }} repository"
          exit 1

      - name: GHA Summary
        run: echo "Secret ${{ matrix.name }} exists" >> $GITHUB_STEP_SUMMARY