name: STATICSITE-VERCEL
run-name: Event handler for 'staticsite-vercel' ( Triggered by ${{ github.event_name }} and run by ${{ github.actor }} )

on:
  repository_dispatch:
    types: [staticsite-vercel]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: none

# Allow one concurrent deployment
concurrency:
  group: 'deployment-vercel'
  cancel-in-progress: false

jobs:

  get-config:
    name: Get config
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: none
    env:
      SOURCE_REPO: ${{ github.event.client_payload.source_repo }}
      RESOURCE_CONFIG_FILE: "resources/static-site-hosting/vercel.yml"
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Read config
        run: |
          PROJECT_ID=$(sr=$SOURCE_REPO yq '.instances[] | select(.type == "static-site-hosting" and .sourceRepo == env(sr)) | .id' $RESOURCE_CONFIG_FILE -r)
          echo $PROJECT_ID

