name: STATICSITE-VERCEL
run-name: Event handler for 'staticsite-vercel' ( Triggered by ${{ github.event_name }} and run by ${{ github.actor }} )

on:
  repository_dispatch:
    types: [staticsite-vercel]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: none

# Allow one concurrent deployment
concurrency:
  group: 'deployment-vercel'
  cancel-in-progress: false

jobs:

  get-config:
    name: Get config
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: none
    env:
      SOURCE_REPO: ${{ format('{0}/{1}', github.event.client_payload.source-repo-owner, github.event.client_payload.source-repo-name ) }}
      RESOURCE_CONFIG_FILE: "resources/static-site-hosting/vercel.yml"
    steps:

      - name: Read config
        run: |
          echo ${{ fromJSON(github.event.client_payload) }}
          PROJECT_ID=$(yq '.instances[] | select(.type == "static-site-hosting" and .sourceRepo == "$SOURCE_REPO") | .id' $RESOURCE_CONFIG_FILE -r)
          echo $PROJECT_ID

